### PR TITLE
Remove Tako usage

### PR DESCRIPTION
**Pull request by andygout**
Jira card: https://financialtimes.atlassian.net/secure/RapidBoard.jspa?rapidView=1051&modal=detail&selectedIssue=CPP-55.

#### References:
- [Financial-Times/next/wiki - How We Manage Our GitHub Repositories](https://github.com/Financial-Times/next/wiki/How-We-Manage-Our-GitHub-Repositories) (i.e. we should now use Biz Ops).

### CODE REVIEW

**Comment by andygout** [comment]
Yeah, I think a major version is required here.

**Comment by apaleslimghost** [comment]
would be great if you could prioritise #117 so there's an easier way to bulk-add repos over text files 🙏

**Comment by andygout** [comment]
👍 I have added to our list of potential candidates for Q3.

**Comment by apaleslimghost** [comment]
oh and by the way, since the current version is 2.0.0-beta.10 i think it's safe to release this as part of a 2.0.0. betas can contain breaking changes

**Comment by andygout** [comment]
> oh and by the way, since the current version is 2.0.0-beta.10 i think it's safe to release this as part of a 2.0.0. betas can contain breaking changes

I was just about to ask that question - thank you!

**Pull request merged**
